// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzinlixkjjanosbsvnze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6aW5saXhramphbm9zYnN2bnplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NDAxMjQsImV4cCI6MjA2MDExNjEyNH0.IPkrRUJJuFknw5jntlwOcjtZKPfUy-xNq1Hdhju6oE0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);